#!/usr/bin/env bash
set -euo pipefail
export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


rm -rf ~/.elan/{toolchains,update-hashes}
cd "$1"

first=19210bcc58535416f6009c53089eeab4ef608b4d
if git merge-base --is-ancestor @ $first; then
    git checkout $first -- scripts/bench/temci-config.run.yml
fi

if [[ -d ./scripts/bench ]]; then
    timeout -s KILL 4h time nix --experimental-features "nix-command flakes" shell github:leanprover/lean4/b81cff8{#nixpkgs.{jq,gnumake},\?dir=tests/bench#temci} -c ./scripts/bench/run
else
    cp $DIR/* "$1"
    timeout -s KILL 4h time nix --experimental-features "nix-command flakes" shell github:leanprover/lean4/b81cff8{#nixpkgs.{jq,gnumake},\?dir=tests/bench#temci} -c ./run
fi
