#!/usr/bin/env bash

set -euxo pipefail

cp -r $(lean --print-prefix) lean
cp lean-wrapper lean/bin/lean
PATH=lean/bin:$PATH temci exec --config temci-config.yml >2
temci report --reporter codespeed2 |\
  jq '(.build | to_entries | group_by(.key | test("~")) | map(from_entries)) as $groups | .build = $groups[0] | . + ($groups[1] | map_values({instructions: .}))'
  # move file metrics starting with "~" from "build" to toplevel and assign them the "instructions" metric
